### ISSUE TITLE
Permissions and Cleanup

### ISSUE THREAD

**Issue by fladna9** [sparkfunX/Skimmer_Scanner#6]
Hi people !

Just few questions :

- Why is the `android.permission.ACCESS_COARSE_LOCATION` and `android.permission.ACCESS_FINE_LOCATION` requested ? Cannot find any use of location, so maybe you should remove it (more and more people look at permissions before installing the app). By the way, the app on the Play Store requires them too.

- As a Xamarin dev, i would advice that you modify the `.gitignore` file to ignore :

```
*.userprefs
bin/
obj/
Tools/
packages/
.vs/
Resource.designer.cs
```

as all these files can be recovered or are not needed to compile :

- `bin/` and `obj/` are compiled code, that should not be _git-ed_, 
- `Tools/` and `packages/` can be restored easily as the package informations are in the _csproj_ file,
- `.vs/` is not needed,
- `Resource.designer.cs` is regenerated on each build.

Thanks for this app, really interesting. Maybe i'll see to add more devices if i have any spare time/resources available.

Cheers,
Max

**Comment by timtheguy** [comment]
Hi Max,
Though I am not a developer on this application, the `android.permission.ACCESS_COARSE_LOCATION` and `android.permission.ACCESS_FINE_LOCATION` are required because of the added transparency added for user data in Android 6.0. In this case, Bluetooth scans can be used to gather information about the location of the user. You can read [more on the Android Developers website.](https://developer.android.com/guide/topics/connectivity/bluetooth.html#Permissions)

All the best,
Tim

**Comment by timtheguy** [comment]
@fladna9 - I've addressed your concerns with regards to the `.gitignore` file and some of the build files populating into the repo. Good catch! 

Tim

**Comment by fladna9** [comment]
@timtheguy 
Hi !
From the link you've sent, seems that only one of the two location is required, like the coarse one. ;)
Didn't saw this page during my search on this topic. But indeed, seems fair because you may locate a user depending on what device is found near him.

No problem for the gitignore, use it on any Xamarin project you work on, it'll be fine ;)

Max
